admin/src/web/controllers/auth.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import redirect, render_template
from flask import url_for
from flask import session
from src.services.user import UserService
from src.errors import database
from src.web.forms.user import LoginForm

auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")
service = UserService()


@auth_blueprint.get("/")
def login():
    login_form = LoginForm()
    """Render del login del sistema"""
    return render_template("auth/login.html", login_form=login_form)


@auth_blueprint.post("/authenticate")
def authenticate():
    """Verifica si los datos son correctos y logea o vuelve a pantalla login"""
    login_form = LoginForm()
    if login_form.validate_on_submit:
        try:
            username = login_form.username.data
            password = login_form.password.data
            user = service.find_by_username_and_pass(username, password)
            session["user"] = user.id
            session["username"] = user.username
            flash("La sesión se inicio correctamente.", "success")
        except database.PermissionDenied as e:
            flash(e, "danger")
            return redirect(url_for("auth.login"))
    return redirect(url_for("home"))


@auth_blueprint.get("/logout")
def logout():
    """Cerrar sesion del sistema"""
    del session["user"]
    session.clear()
    flash("La sesion se cerro correctamente.", "success")

    return redirect(url_for("auth.login"))

admin/src/web/controllers/user.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask import session
from services.movement import MovementService

from src.services.settings import SettingsService
from src.services.utils import hash_pass
from src.services.utils import verify_pass
from src.web.helpers.auth import is_member, login_required, verify_permission
from src.services.user import UserService
from src.services.movement import MovementService
from src.services.member import MemberService
from src.web.forms.user import (
    CreateUserForm,
    UpdateUserForm,
    SearchUserForm,
    FilterUsersForm,
    AddRolesForm,
    DeleteRolesForm,
    UnlinkMemberForm,
    UpdatePassForm
)
from src.web.forms.member import FilterSearchForm
from src.errors import database


user_blueprint = Blueprint("users", __name__, url_prefix="/users")

service = UserService()
member_service = MemberService()
settings = SettingsService()
movementService = MovementService()


@user_blueprint.route("/", methods=["GET"])
@login_required
@verify_permission("user_index")
def index():
    filter_form = FilterUsersForm()
    """Render de la lista de usuarios paginada"""
    filter = request.args.get("filter")
    page = request.args.get("page", 1, type=int)
    users_paginator = service.list_paginated_users(
        page, settings.get_items_per_page(), "users.index", filter
    )
    return render_template(
        "users/index.html",
        filter_form=filter_form,
        paginator=users_paginator,
    )


@user_blueprint.route("/filter_users_by", methods=["POST"])
@login_required
@verify_permission("user_search")
def users_filter_by():
    filter_form = FilterUsersForm()

    if filter_form.validate_on_submit:

        page = request.args.get("page", 1, type=int)
        filter = filter_form.filter.data
        users_paginator = service.list_paginated_users(
            page, settings.get_items_per_page(), "users.index", filter
        )
        return render_template(
            "users/index.html",
            paginator=users_paginator,
            filter_form=filter_form,
        )


@user_blueprint.route("/add", methods=["POST", "GET"])
@login_required
@verify_permission("user_create")
def users_add():
    """Agrega usuarios mediante el formulario"""
    form = CreateUserForm()

    if form.validate_on_submit():

        role = service.find_role_by_name(form.roles.data)
        email = form.email.data
        username = form.username.data
        first_name = form.first_name.data
        password = hash_pass(form.email.data)
        last_name = form.last_name.data
        roles = [role]

        try:
            service.create_user(
                email=email,
                username=username,
                password=password,
                first_name=first_name,
                last_name=last_name,
                roles=roles,
            )
            flash("Usuario creado con éxito!", "success")
        except database.ExistingData as e:
            flash(e, "danger")
    return render_template("users/add_user.html", form=form)


@user_blueprint.route("/update/<id>", methods=["POST", "GET"])
@login_required
@verify_permission("user_update")
def users_update(id):
    form = UpdateUserForm()
    user = service.find_user_by_id(id)

    if request.method == "POST":
        if form.validate_on_submit():
            email = form.email.data
            username = form.username.data
            first_name = form.first_name.data
            last_name = form.last_name.data

            try:
                service.update_user(
                    id=id,
                    email=email,
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                )
                flash("Usuario actualizado con éxito!", "success")
            except database.ExistingData as e:
                flash(e, "danger")

    return render_template("users/update.html", user=user, form=form)


@user_blueprint.route("/block_user/<id>", methods=["GET"])
@login_required
@verify_permission("user_update")
def users_block(id):
    user = service.find_user_by_id(id)

    try:

        user_session = session["user"]
        service.block_user(id, user_session)
        if user.is_active == False:
            flash("Usuario bloqueado con éxito", "success")
        else:
            flash("Usuario desbloqueado con éxito", "success")
    except database.PermissionDenied as e:
        flash(e, "danger")

    return redirect(url_for("users.index"))


@user_blueprint.route("/search_user", methods=["POST", "GET"])
@login_required
@verify_permission("user_search")
def users_search():
    search_form = SearchUserForm()
    unlink_form = UnlinkMemberForm()

    if request.method == "POST":
        delete_roles_form = DeleteRolesForm()
        add_roles_form = AddRolesForm()

        if search_form.validate_on_submit():
            email = search_form.email.data
            user = service.find_user_byEmail(email)
            return render_template(
                "users/user_info.html",
                user=user,
                add_roles_form=add_roles_form,
                delete_roles_form=delete_roles_form,
                unlink_form=unlink_form
            )
    else:
        return render_template("users/search.html", search_form=search_form)


@user_blueprint.route("/user_info/<id>", methods=["GET", "POST"])
@login_required
@verify_permission("user_show")
def user_info(id):
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()

    user = service.find_user_by_id(id)
    return render_template(
        "users/user_info.html",
        user=user,
        add_roles_form=add_roles_form,
        delete_roles_form=delete_roles_form,
        unlink_form=unlink_form,
    )


@user_blueprint.route("/add_roles/<id>", methods=["POST", "GET"])
@login_required
@verify_permission("user_update")
def users_add_roles(id):
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()
    user = service.find_user_by_id(id)

    if request.method == "POST":

        if add_roles_form.validate_on_submit:
            role = add_roles_form.roles.data

            try:
                service.add_role(id, role)
                flash("Rol agregado con éxito!", "success")
            except database.ExistingData as e:
                flash(e, "danger")
            except database.PermissionDenied as e:
                flash(e, "danger")
        return render_template(
            "users/user_info.html",
            user=user,
            add_roles_form=add_roles_form,
            delete_roles_form=delete_roles_form,
            unlink_form=unlink_form,
        )
    else:
        return render_template(
            "users/user_info.html",
            user=user,
            add_roles_form=add_roles_form,
            delete_roles_form=delete_roles_form,
            unlink_form=unlink_form,
        )


@user_blueprint.route("/delete_roles/<id>", methods=["POST", "GET"])
@login_required
@verify_permission("user_update")
def users_delete_roles(id):
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()
    user = service.find_user_by_id(id)
    roles = service.list_user_roles(id)
    if request.method == "POST":
        if delete_roles_form.validate_on_submit:
            try:
                role = delete_roles_form.role.data
                service.remove_role(id, role)
                flash("Rol eliminado con éxito!", "success")
            except database.PermissionDenied as e:
                flash(e, "danger")
    return render_template(
        "users/user_info.html",
        user=user,
        roles=roles,
        delete_roles_form=delete_roles_form,
        add_roles_form=add_roles_form,
        unlink_form=unlink_form,
    )


@user_blueprint.route("/profile", methods=["GET"])
@login_required
def profile():
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()
    id = session["user"]

    user = service.find_user_by_id(id)
    return render_template(
        "users/profile.html",
        user=user,
        delete_roles_form=delete_roles_form,
        add_roles_form=add_roles_form,
        unlink_form=unlink_form
    )


@user_blueprint.route("/delete/<id>", methods=["GET"])
@login_required
@verify_permission("user_destroy")
def delete(id):
    filter_form = FilterUsersForm()
    session_id = session["user"]

    try:
        service.delete(id, session_id)
        flash("Usuario eliminado con éxito!", "success")
    except database.PermissionDenied as e:
        flash(e, "danger")
    users = service.list_users()
    return render_template("users/index.html", users=users, filter_form=filter_form)


@user_blueprint.route("/estado_societario/", methods=["GET"])
@login_required
@is_member
def memberState():
    filter_form = FilterSearchForm()
    page = request.args.get("page", 1, type=int)
    filter = request.args.get("filter")
    search = request.args.get("search")
    member_paginator = member_service.list_paginated_members(
        page, settings.get_items_per_page(), "users.memberState", filter, search, True
    )
    return render_template(
        "users/member_state.html", filter_form=filter_form, paginator=member_paginator
    )

@user_blueprint.route("/lista_movimientos/<member_id>", methods=["GET"])
@login_required
def viewMovements(member_id):
    member = member_service.get_by_membership_number(member_id)
    balance = movementService.get_balance(member, all=True)
    page = request.args.get("page", 1, type=int)

    paginator = movementService.list_paginated_movements(
        page,
        settings.get_items_per_page(),
        'users.viewMovements',
        member
    )

    return render_template(
        "users/view_movements.html",
        member=member,

admin/src/web/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Club Deportivo Villa Elisa</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav w-100">
      {% if is_authenticated(session) %}
      {% if is_administrator(session) or is_operator(session)%}

          {% if is_administrator(session) %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{{url_for('users.index')}}" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Usuarios
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="{{url_for('users.index')}}">Todos los usuarios</a></li>
              <li><a class="dropdown-item" href="{{url_for('users.users_add')}}">Agregar nuevo usuario</a></li>
              <li><a class="dropdown-item" href="{{url_for('users.users_search')}}">Buscar un Usuario</a></li>
            </ul>
          </li>
          {% endif %}

          <li class="nav-item">
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="{{url_for('members.index')}}" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    Socios
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" href="{{url_for('members.index')}}">Todos los Socios</a></li>
                    <li><a class="dropdown-item" href="{{url_for('members.filter_by_doc')}}">Buscar un socio</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('discipline.index')}}">Disciplinas</a>
          </li>
        {% endif %}
        <div class="w-100 d-flex flex-row-reverse">
          {% if is_authenticated(session) %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{session.username}}
              </a>
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark">
                <li><a class="dropdown-item" href="{{url_for('users.profile')}}">Ver mis Datos</a></li>
                <li><a class="dropdown-item" href="{{url_for('users.update_password')}}">Cambiar mi contraseña</a></li>
                {% if is_member(session) %}
                  <li><a class="dropdown-item" href="{{url_for('users.memberState')}}" >Estado societario</a></li> 
                {% endif %}
                <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Cerrar sesión</a></li>
              </ul>
            </li>
            {% if is_administrator(session) %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('settings.index')}}">Configuraciones</a>
              </li>
            {% endif %}
          {% endif %}
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.login')}}">Iniciar sesión</a>
            </li>
          {% endif %}
        </div>
      </ul>
    </div>
  </div>
</nav>

admin/src/web/templates/partials/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
   {% if messages %}
      {% for category, message in messages %}

         <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>

      {% endfor %}
   {% endif %}
{% endwith %}

admin/src/web/templates/partials/paginator.html
<nav aria-label="...">
    <ul class="pagination">
        {% if paginator.pages %}
            {% if paginator.prev_url %}
            <li class="page-item">
            <a class=page-link href="{{ paginator.prev_url }}">Anterior </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link">Anterior</a>
            </li>
            {% endif %}
            {% for page in paginator.pages %}
                    {% if page != paginator.page %}
                        {% if page %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for(paginator._endpoint, page=page, member_id=paginator.member_id, filter=paginator.filter,
                                    search=paginator.search) }}">
                                    {{ page }} 
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <span class="page-link">...</span>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link">{{ page }}</a>
                        </li>
            {% endif %}

            {% endfor %}


            {% if paginator.next_url %}
            <li class="page-item">
                <a class=page-link href="{{ paginator.next_url }}">Siguiente</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link">Siguiente</a>
            </li>
            {% endif %}
        {% endif %}
    </ul>
</nav>