admin/src/web/forms/discipline.py
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, SubmitField, IntegerField, BooleanField
from wtforms.validators import InputRequired, NumberRange, Length, Optional


class DisciplineBaseForm(FlaskForm):
    name = StringField("Disciplina", validators=[InputRequired()])
    category = StringField("Categoria", validators=[InputRequired()])
    instructor = StringField("Instructor/es", validators=[InputRequired()])
    days_and_schedules = StringField("Día y Horario", validators=[InputRequired()])
    registration_quota = IntegerField(
        "Cupos", validators=[InputRequired(), NumberRange(min=1)]
    )
    pays_per_year = IntegerField(
        "Pagos por año", validators=[InputRequired(), NumberRange(min=1)]
    )
    amount = DecimalField("Precio", validators=[InputRequired(), NumberRange(min=0)])
    is_active = BooleanField("¿Activa?", default=True, validators=[Optional()])


class CreateDisciplineForm(DisciplineBaseForm):
    submit = SubmitField("Guardar")


class UpdateDisciplineForm(CreateDisciplineForm):
    submit = SubmitField("Actualizar")

admin/src/web/forms/discipline/forms.py
from wsgiref.validate import validator
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField
from wtforms.validators import DataRequired, NumberRange, Length

class CreateDisciplineForm(FlaskForm):
    name = StringField("Disciplina", validators=[DataRequired()])
    category = StringField("Categoria", validators=[DataRequired()])
    instructor_first_name = StringField("Nombre del Instructor", validators=[DataRequired()])
    instructor_last_name = StringField("Apellido del Instructor", validators=[DataRequired()])
    days_and_schedules = StringField("Día y Horario", validators=[DataRequired()])
    amount = DecimalField("Precio", validators=[DataRequired(), NumberRange(min=0)])

admin/src/web/controllers/discipline.py
import datetime
from decimal import Decimal
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask import session

from src.errors import database
from src.web.forms.discipline import CreateDisciplineForm, UpdateDisciplineForm
from src.web.helpers.auth import login_required, verify_permission

from src.services.discipline import DisciplineService
from src.services.settings import SettingsService
from src.services.suscription import SuscriptionService


# Se define Blueprint de Usuario
discipline_blueprint = Blueprint("discipline", __name__, url_prefix="/disciplinas")

service_discipline = DisciplineService()
service_settings = SettingsService()
service_suscription = SuscriptionService()

@discipline_blueprint.get("/")
@login_required
@verify_permission("discipline_index")
def index():
    """Render de la lista de disciplinas con paginación"""
    page = request.args.get("page", 1, type=int)
    discipline_paginator = service_discipline.list_paginated_disciplines(
        page, service_settings.get_items_per_page(), "discipline.index"
    )
    return render_template("disciplines/index.html", paginator=discipline_paginator)

@discipline_blueprint.route("/create", methods=["GET", "POST"])
@login_required
@verify_permission("discipline_create")
def create():
    form = CreateDisciplineForm()

    if form.validate_on_submit():

        name = form.name.data
        category = form.category.data
        instructor = form.instructor.data
        days_and_schedules = form.days_and_schedules.data
        registration_quota = form.registration_quota.data
        pays_per_year = form.pays_per_year.data
        amount = form.amount.data
        is_active = form.is_active.data

        try:
            service_discipline.create_discipline(
                name=name,
                category=category,
                instructor=instructor,
                days_and_schedules=days_and_schedules,
                registration_quota=registration_quota,
                pays_per_year=pays_per_year,
                amount=amount,
                is_active=is_active,
            )
            flash("Disciplina creada con éxito", "success")
            return redirect(url_for("discipline.index"))
        except database.MinValueValueError as e:
            flash(str(e), "danger")
        except database.ExistingData as e:
            flash(f"La disciplina: {name} - {category} ya existe.", "danger")

    return render_template("disciplines/create.html", form=form)


@discipline_blueprint.route("/update/<int:discipline_id>", methods=["GET", "POST"])
@login_required
@verify_permission("discipline_update")
def update(discipline_id):
    form = UpdateDisciplineForm()

    if request.method == "GET":
        discipline = service_discipline.find_discipline(id=discipline_id)
        form.name.data = discipline.name
        form.category.data = discipline.category
        form.instructor.data = discipline.instructor
        form.days_and_schedules.data = discipline.days_and_schedules
        form.registration_quota.data = discipline.registration_quota
        form.pays_per_year.data = discipline.pays_per_year
        form.amount.data = discipline.amount
        form.is_active.data = discipline.is_active
        # discipline_id = discipline_id

    else:
        if form.validate_on_submit():
            name = form.name.data
            category = form.category.data
            instructor = form.instructor.data
            days_and_schedules = form.days_and_schedules.data
            registration_quota = form.registration_quota.data
            pays_per_year = form.pays_per_year.data
            amount = form.amount.data
            is_active = form.is_active.data

            try:
                service_discipline.update_discipline(
                    id=discipline_id,
                    name=name,
                    category=category,
                    instructor=instructor,
                    days_and_schedules=days_and_schedules,
                    registration_quota=registration_quota,
                    pays_per_year=pays_per_year,
                    amount=amount,
                    is_active=is_active,
                )
                flash("Disciplina actualizada con éxito", "success")
                return redirect(url_for("discipline.index"))
            except database.MinValueValueError as e:
                flash(str(e), "danger")
            except database.ExistingData as e:
                flash(f"La disciplina: {name} - {category} ya existe.", "danger")
            except database.UpdateError as e:
                flash(str(e), "danger")

    return render_template(
        "disciplines/update.html", form=form, discipline_id=discipline_id
    )


@discipline_blueprint.post("/delete/<int:discipline_id>")
@login_required
@verify_permission("discipline_destroy")
def delete(discipline_id):
    if service_discipline.delete_discipline(discipline_id):
        flash("Disciplina eliminada correctamente", "success")

    return redirect(url_for("discipline.index"))

admin/src/web/templates/disciplines/create.html
{% extends "layout.html" %}
{% block title %}Alta de Disciplina{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Alta de Disciplina</h1>
        </div>
    </div>
    <form action="{{ url_for('discipline.create')}}" method="post">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    {{ form.name(class_="form-control", placeholder="Nombre de la disciplina", size=32)}}
                </div>
            </div>
            <div class="col">
                <div class="input-group mb-3">
                    {{ form.category(class_="form-control", placeholder="Nombre de la categoria")}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    {{ form.instructor(class_="form-control", placeholder="Instructor/es")}}
                </div>
            </div>
        </div>

        <div class="form-group mb-3">
            {{ form.days_and_schedules(class_="form-control", placeholder="Días y horarios")}}
        </div>
        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.registration_quota(class_="form-control", placeholder="Cupo")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.pays_per_year(class_="form-control", placeholder="Pagos por año")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.amount(class_="form-control", placeholder="Valor")}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group mb-3">
                <div class="col-sm-12 d-flex justify-content-center">
                    {{ form.is_active.label }}
                    {{ form.is_active(class_="form-check-input", value="n") }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group mb-3">
                <div class="col-sm-12 d-flex justify-content-center">
                    {{ form.submit(class="btn btn-success") }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                <a href="{{url_for('discipline.index')}}"> Volver </a>
            </div>
        </div>
    </form>
</div>



{% endblock %}

admin/src/web/templates/disciplines/index.html
{% extends "layout.html" %}
{% block title %}Consultas Disciplinas{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Disciplinas</h1>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Disciplina</th>
                <th>Categoria</th>
                <th>Instructores</th>
                <th>Dias y Horarios</th>
                <th>Monto</th>
                <th>Cupo</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for discipline in paginator.items %}
            <tr>
                <td>{{ discipline.name }}</td>
                <td>{{ discipline.category }}</td>
                <td>{{ discipline.instructor }} </td>
                <td>{{ discipline.days_and_schedules }}</td>
                <td>{{ discipline.amount }}</td>
                <td>{{ discipline.registration_quota }}</td>
                <td>
                    <div class="row">
                        {% if discipline.is_active %}
                        <span class="btn btn-sm btn-success rounded-pill d-inline">Activa</span>
                        {% else %}
                        <span class="btn btn-sm btn-dark rounded-pill d-inline">Inactiva</span>
                        {% endif %}
                    </div>
                </td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Seleccionar
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item"
                                    href="{{ url_for('discipline.update', discipline_id=discipline.id) }}">Editar</a>
                            </li>
                            {% if discipline.membership.is_active %}
                                <li><a class="dropdown-item"
                                        href="{{ url_for('suscription.index', discipline_id=discipline.id, has_quota=discipline.has_quota) }} ">Inscripciones</a>
                                </li>
                            {% endif %}
                            <li>
                                {% if can_do_it(session, 'discipline_destroy') %}
                                <button class="dropdown-item" type="button" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal{{ discipline.id }}">
                                    Eliminar
                                </button>
                                {% endif %}

                            </li>

                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include('partials/paginator.html') %}
    {% if can_do_it(session, 'discipline_create') %}
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                <a class="btn btn-secondary" href="{{url_for('discipline.create')}}">Alta de una disciplina</a>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-center">
            <a href="{{url_for('home')}}"> Volver </a>
        </div>
    </div>
</div>


{% for discipline in paginator.items %}
<div class="modal fade" id="deleteModal{{ discipline.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Baja</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Se va a dar de baja la disciplina {{discipline.discipline_name}}.
                (Se daran de baja todas las inscripciones)
                ¿Está Seguro?
            </div>
            <form action="{{url_for('discipline.delete', discipline_id=discipline.id)}}" method="POST">

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Si</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}


{% endblock %}

admin/src/web/templates/disciplines/update.html
{% extends "layout.html" %}
{% block title %}Modificacion de Disciplina{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Modificación de Disciplina</h1>
        </div>
    </div>
    <form action="{{ url_for('discipline.update', discipline_id=discipline_id)}}" method="post">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    {{ form.name(class_="form-control", placeholder="Nombre de la disciplina", size=32)}}
                </div>
            </div>
            <div class="col">
                <div class="input-group mb-3">
                    {{ form.category(class_="form-control", placeholder="Nombre de la categoria") }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    {{ form.instructor(class_="form-control", placeholder="Instructores") }}
                </div>
            </div>
        </div>

        <div class="form-group mb-3">
            {{ form.days_and_schedules(class_="form-control", placeholder="Días y horarios") }}
        </div>

        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.registration_quota(class_="form-control", placeholder="Cupo")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.pays_per_year(class_="form-control", placeholder="Pagos por año")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.amount(class_="form-control", placeholder="Valor")}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group mb-3">
                <div class="col-sm-12 d-flex justify-content-center">
                    {{ form.is_active.label }}
                    {{ form.is_active(class_="form-check-input", value="n") }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group mb-3">
                <div class="col-sm-12 d-flex justify-content-center">
                    {{ form.submit(class="btn btn-success") }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                <a href="{{url_for('discipline.index')}}"> Volver </a>
            </div>
        </div>
    </form>
</div>


{% endblock %}