admin/src/web/forms/member.py
from flask import flash
from flask_wtf import FlaskForm
from traitlets import default
from wtforms import StringField, SubmitField, SelectField, EmailField
from wtforms.validators import (
    InputRequired,
    Email,
    Optional,
    DataRequired,
    Length,
    ValidationError,
)


class MemberForm(FlaskForm):
    first_name = StringField("Nombre", validators=[InputRequired()])
    last_name = StringField("Apellido", validators=[InputRequired()])
    document_type = SelectField(
        "Tipo de Documento", choices=["DNI", "LE", "LC", "PASAPORTE"]
    )
    document_number = StringField(
        "Número de Documento", validators=[InputRequired(), Length(min=8, max=10)]
    )

    def validate_document_number(form, field):
        if not field.data.isdigit():
            flash("Solo caracteres numéricos para el N° de Documento", "danger")
            raise ValidationError()

    gender = SelectField("Género", choices=["M", "F", "Otro"])
    address = StringField("Domicilio", validators=[InputRequired()])
    email = EmailField("Email", validators=[Optional(), Email()])
    phone_number = StringField("Teléfono")
    submit = SubmitField("Guardar")


class FilterSearchForm(FlaskForm):
    filter = SelectField(
        "Filtro",
        choices=[
            ("Todos", "Todos"),
            ("Activos", "Activos"), 
            ("Inactivos", "Inactivos"),
        ], default=("Todos")
    )
    search = StringField("Apellido")
    submit = SubmitField("Filtrar")


class FilterByDocForm(FlaskForm):
    document_number = StringField(
        "Número de Documento", validators=[DataRequired(), Length(min=8, max=10)]
    )
    document_type = SelectField(
        "Tipo de Documento", choices=["DNI", "LE", "LC", "PASAPORTE"]
    )
    submit = SubmitField("Buscar Socio")

    

admin/src/web/controllers/license.py
import os
import imghdr
import base64
from pathlib import Path
from flask import (
    Flask,
    flash,
    current_app,
    render_template,
    request,
    redirect,
    url_for,
    abort,
    Blueprint,
    send_file
)
from werkzeug.utils import secure_filename

from src.models.database import db

from src.services.member import MemberService
from src.services.movement import MovementService
from src.web.forms.license.forms import PictureForm
from src.web.helpers.auth import login_required, verify_permission

_service_member = MemberService()
_service_movement = MovementService()
app = current_app
license_blueprint = Blueprint("license", __name__, url_prefix="/carnet")


def validate_image(stream):
    header = stream.read(512)
    stream.seek(0)
    format = imghdr.what(None, header)
    if not format:
        return None
    return "." + (format if format != "jpeg" else "jpg")


@license_blueprint.get("/<id>")
def index(id):
    form = PictureForm()
    return render_template("license/index.html", form=form, id=id)


@license_blueprint.post("/crop/<id>")
def crop_picture(id):
    uploaded_file = request.files.get("picture")
    if uploaded_file:
        filename = secure_filename(uploaded_file.filename)
        if filename != "":
            file_ext = os.path.splitext(filename)[1]
            if file_ext not in app.config[
                "UPLOAD_EXTENSIONS"
            ] or file_ext != validate_image(uploaded_file.stream):
                abort(400)

        member_picture = base64.b64encode(uploaded_file.read())
        file_type = uploaded_file.content_type
        return render_template(
            "license/crop.html",
            file_type=file_type,
            file=member_picture.decode("utf-8"),
            member_id=id,
        )
    return redirect(url_for("license.index"))


@license_blueprint.post("/upload")
def upload_picture():
    member_id = request.form.get("member_id")
    member = _service_member.get_by_membership_number(member_id)
    cropped_photo = request.form.get("cropped_img")
    cropped_photo_type = request.form.get("cropped_img_type")
    if cropped_photo:
        binary_photo = cropped_photo.split(",")[1].encode("utf-8")
        result = _service_member.save_member_photo(
            member, cropped_photo_type, binary_photo
        )
        if result:
            flash("Imagen guardada con éxito!", "success")
        else:
            flash("Error al salvar la foto", "danger")

    return redirect(url_for("members.index"))


@license_blueprint.get("/plantillaCarnet/<id>")
@login_required
@verify_permission("member_show")
def view_carnet(id):
    member = _service_member.get_by_membership_number(id)
    if member.picture is None:
        flash(
            "No se pude visualizar el carnet si el socio no posee imagen asignada",
            "danger",
        )
        return redirect(url_for("members.index"))
    else:
        file = member.picture.image
        file_type = member.picture.image_type
        qr_img = member.picture.qr_image
        is_defaulter = _service_movement.is_defaulter(member)
        return render_template(
            "license/carnet.html",
            member=member,
            is_defaulter=is_defaulter,
            file_type=file_type,
            file=file.decode("utf-8"),
            qr=qr_img.decode("utf-8"),
        )


@license_blueprint.get("/exportPdf/<id>")
@verify_permission("member_show")
def export_pdf(id):
    license_pdf = _service_member.license_to_pdf(id)
    filename = license_pdf._filename
    return send_file(
            filename,
            mimetype="text/pdf",
            download_name="report.pdf",
            as_attachment=True,
        )
   

admin/src/web/controllers/member.py
from pathlib import Path
from flask import (
    Blueprint,
    request,
    render_template,
    flash,
    redirect,
    url_for,
    send_file,
)

from src.services.member import MemberService
from src.services.settings import SettingsService
from src.services.suscription import SuscriptionService
from src.web.forms.member import (
    FilterByDocForm,
    MemberForm,
    FilterSearchForm,
)
from src.errors import database
from src.web.helpers.auth import login_required, verify_permission


# Se define Blueprint de Socio
member_blueprint = Blueprint("members", __name__, url_prefix="/socios")

service = MemberService()
setting = SettingsService()


@member_blueprint.get("/")
@login_required
@verify_permission("member_index")
def index():
    filter_form = FilterSearchForm()
    page = request.args.get("page", 1, type=int)
    filter = request.args.get("filter")
    search = request.args.get("search")
    member_paginator = service.list_paginated_members(
        page, setting.get_items_per_page(), "members.index", filter, search
    )
    return render_template(
        "members/index.html", filter_form=filter_form, paginator=member_paginator
    )


@member_blueprint.route("/create", methods=["GET", "POST"])
@login_required
@verify_permission("member_create")
def create():
    """Por metodo POST toma del request los datos y se los pasa al modelo para que agregue un Socio,
    si no lo puede agregar lo informa"""
    form = MemberForm()
    if form.validate_on_submit():

        first_name = form.first_name.data
        last_name = form.last_name.data
        document_type = form.document_type.data
        document_number = form.document_number.data
        gender = form.gender.data
        address = form.address.data
        email = form.email.data
        phone_number = form.phone_number.data

        try:
            service.create_member(
                first_name=first_name,
                last_name=last_name,
                document_type=document_type,
                document_number=document_number,
                gender=gender,
                address=address,
                email=email,
                phone_number=phone_number,
            )
            flash("Socio guardado con éxito!", "success")
            return redirect(url_for("members.index"))
        except database.ExistingData as e:
            flash(e, "danger")
    return render_template("members/create.html", form=form)


@member_blueprint.route("/update/<int:member_id>", methods=["GET", "POST"])
@login_required
@verify_permission("member_update")
def update(member_id):
    """Por metodo POST toma del request los datos y se los pasa al modelo para que agregue un Socio,
    si no lo puede agregar lo informa"""
    form = MemberForm()
    if request.method == "GET":
        member = service.get_by_membership_number(id=member_id)
        form.first_name.data = member.first_name
        form.last_name.data = member.last_name
        form.document_type.data = member.document_type
        form.document_number.data = member.document_number
        form.gender.data = member.gender
        form.address.data = member.address
        form.email.data = member.email
        form.phone_number.data = member.phone_number

    else:
        if form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            document_type = form.document_type.data
            document_number = form.document_number.data
            gender = form.gender.data
            address = form.address.data
            email = form.email.data
            phone_number = form.phone_number.data

        try:
            service.update_member(
                id=member_id,
                first_name=first_name,
                last_name=last_name,
                document_type=document_type,
                document_number=document_number,
                gender=gender,
                address=address,
                email=email,
                phone_number=phone_number,
            )
            flash("Socio actualizado con éxito!", "success")
            return redirect(url_for("members.index"))
        except database.ExistingData as e:
            flash(e, "danger")
    return render_template("members/update.html", form=form, member_id=member_id)


@member_blueprint.post("/change_activity/<int:member_id>")
@login_required
@verify_permission("member_change_activity")
def change_activity(member_id):
    change = service.change_activity_member(member_id)
    if not change:
        flash("El socio es moroso no se puede activar", "warning")
    return redirect(url_for("members.index"))


@member_blueprint.route("/filter_by", methods=["POST", "GET"])
@verify_permission("member_index")
def filter_by():
    filter_form = FilterSearchForm()
    if filter_form.validate_on_submit:
        page = request.args.get("page", 1, type=int)
        filter = filter_form.filter.data
        search = filter_form.search.data
        members_paginator = service.list_paginated_members(
            page, setting.get_items_per_page(), "members.index", filter, search
        )
        return render_template(
            "members/index.html", paginator=members_paginator, filter_form=filter_form
        )


@member_blueprint.route("/filter_by_dni", methods=["POST", "GET"])
@verify_permission("member_index")
def filter_by_doc():
    filter_form = FilterByDocForm()
    if request.method == "POST":
        if filter_form.validate_on_submit():
            doc_type = filter_form.document_type.data
            doc_number = filter_form.document_number.data
            member = service.find_member(doc_type, doc_number)
            return render_template("members/member_info.html", member=member)
    else:
        return render_template("members/search.html", filter_form=filter_form)


@member_blueprint.route("/member_info/<id>", methods=["GET"])
@verify_permission("member_show")
def member_info(id):
    member = service.get_by_membership_number(id)
    return render_template("members/member_info.html", member=member)


@member_blueprint.get("/export_list")
@verify_permission("member_index")
def export_list():
    filter_by_status = request.args.get("filter_by_status")
    filter_by_last_name = request.args.get("filter_by_last_name")
    export_select = request.args.get("export_select")
    members = service.members_for_export(filter_by_status, filter_by_last_name)
    if export_select == "pdf":
        report = service.export_list_to_pdf(members, setting.get_items_per_page())
        filename = Path(report._filename).name
        return render_template("members/view_report.html", filename=filename)
    else:
        report = service.export_list_to_csv(members)
        filename = report.name
        return send_file(
            filename,
            mimetype="text/csv",
            download_name="report.csv",
            as_attachment=True,
        )

admin/src/web/templates/members/create.html
{% extends "layout.html" %}
{% block title %}Agregar Socio{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Agregar Socio</h1>
        </div>
    </div>
    <form action="{{ url_for('members.create') }}" method="post">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col">
                <div class="from-group mb-3">
                    {{ form.first_name.label}}
                    {{ form.first_name(class_="form-control", placeholder="Nombre")}}
                </div>
            </div>
        </div>
        <div class="row">    
            <div class="col">
                <div class="from-group mb-3">
                    {{ form.last_name.label}}
                    {{ form.last_name(class_="form-control", placeholder="Apellido")}}
                </div>
            </div>
        </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col">
                <div class="form-group mb-3">
                    {{ form.document_type.label}}
                    {{ form.document_type(class_="form-control")}}
                </div>
            </div>
            <div class="col">
                <div class="form-group mb-3">
                    {{ form.document_number.label}}
                    {{ form.document_number(class_="form-control", placeholder="Número de Documento")}}
                </div>
            </div>
            <div class="col">
                <div class="form-group mb-3">
                    {{ form.gender.label }}
                    {{ form.gender(class_="form-control")}}
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.address.label }}
                    {{ form.address(class_="form-control", placeholder="Domicilio")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.email.label }}
                    {{ form.email(class_="form-control", placeholder="Email")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.phone_number.label }}
                    {{ form.phone_number(class_="form-control", placeholder="Télefono")}}
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                {{ form.submit(class="btn btn-success") }}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                <a href="{{url_for('members.index')}}"> Volver </a>
            </div>
        </div>
    </form>
</div>



{% endblock %}

admin/src/web/templates/members/index.html
{% extends "layout.html" %}
{% block title %}Modulo de Socios{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
    <h1 class="text-center">Socios</h1>

    <div class="row my-3">


        <div class="col-9">
            <h4>Filtrar listado por: </h4>
            <form class="d-flex" action="{{ url_for('members.filter_by')}}" method="post">
                <div class="form group my-2">
                    {{ filter_form.filter(class="", id="filter_by_status") }}
                    <div class="form-grpup my-2">
                        {{ filter_form.search(class="form-control me-2", placeholder="Busqueda por Apellido",
                        id="filter_by_last_name") }}
                    </div>

                    {{ filter_form.hidden_tag() }}
                    <button class="btn btn btn-primary block" type="submit">Filtrar</button>
                </div>
            </form>
        </div>

        <div class="col-3">
            <h4 class="text-center">Exportar listado</h4>
            <div class="d-flex justify-content-center">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <input class="btn btn-sm btn-success rounded-pill d-inline" type="submit"
                            onclick="return post_export()" value="Exportar en:">
                    </div>
                    <select class="custom-select" id="export_select">
                        <option selected value="pdf">PDF</option>
                        <option value="csv">CSV</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

<div class="row">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>N° de Socio</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo de Documento</th>
                <th>N° de Documento</th>
                <th>Género</th>
                <th>Está Activo?</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for member in paginator.items %}
            <tr>
                <td>{{ member.membership_number }}</td>
                <td>{{ member.first_name }}</td>
                <td>{{ member.last_name }}</td>
                <td>{{ member.document_type }}</td>
                <td>{{ member.document_number}}</td>
                <td>{{ member.gender }}</td>
                <td>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal"
                        data-bs-target="#staticBackdrop{{member.membership_number}}">
                        {% if member.is_active%}
                        {{"Sí"}}
                        {% else %}
                        {{"No"}}
                        {% endif %}
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="staticBackdrop{{member.membership_number}}" data-bs-backdrop="static" data-bs-keyboard="false"
                        tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="staticBackdropLabel">                        
                                        {% if member.is_active%}
                                        {{"Desactivar socio"}}
                                        {% else %}
                                        {{"Activar socio"}}
                                        {% endif %}
                                    </h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Está seguro de que desea 
                                    {% if member.is_active%}
                                    {{" desactivar el socio"}}
                                    {% else %}
                                    {{" activar el socio"}}
                                    {% endif %}
                                    {{ member.membership_number }}
                                </div>
                                <form method="post"
                                action="{{ url_for('members.change_activity', member_id=member.membership_number)}}">
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Cancelar</button>
                                    <button type="submit" class="btn btn-primary">Sí</button>
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-outline-secondary dropdown-toggle" type="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Acciones
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('members.member_info',
                                id=member.membership_number)}}">Ver Socio</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('members.update',
                            member_id=member.membership_number)}}">Editar</a>
                            </li>
                            <li><a class="dropdown-item" href="{{url_for('movements.member_balance', member_id=member.membership_number)}}">Pagos</a></li>
                            {% if not member.user_id and member.is_active %}
                            <li><a class="dropdown-item" href="{{url_for('users.link_user', id=member.membership_number)}}">Asignar usuario</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{{url_for('license.index', id=member.membership_number)}}">Subir Foto</a></li>
                            <li><a class="dropdown-item" href="{{url_for('license.view_carnet', id=member.membership_number)}}">Ver carnet</a></li>
                        </ul>
                    </div>
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include('partials/paginator.html') %}

    </div>
    
    <div class="row my-3">
        <div class="col-sm-12 d-flex justify-content-center">
            <a class="btn btn-secondary btn-lg" href="{{url_for('members.create')}}">Agregar Socio</a>
        </div>
    </div>


    <div class="row my-2">
        <div class="col-sm-12 d-flex justify-content-center">
            <a class="btn btn-primary btn-sm" href="{{url_for('home')}}"> Volver </a>
        </div>
    </div>

</div>
{% block javascripts %}
<script>

    function post_export() {

        window.open("./export_list?filter_by_status=" +
            document.getElementById("filter_by_status").value + "&filter_by_last_name=" +
            document.getElementById("filter_by_last_name").value + "&export_select=" +
            document.getElementById("export_select").value)
    }   
</script>
{% endblock javascripts %}



{% endblock content %}

admin/src/web/templates/members/member_info.html
{% extends "layout.html" %}
{% block title %}Modulo de Socios{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

{% if member %} 
<div class="container">
    <h1 class="text-center"> Socio</h1>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>N° de Socio</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo de Documento</th>
                <th>N° de Documento</th>
                <th>Género</th>
                <th>Está Activo?</th>
                {%if member.user_id %}
                <th>Usuario</th>
                {% endif %}
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>{{ member.membership_number }}</th>
                <th>{{ member.first_name }}</th>
                <th>{{ member.last_name }}</th>
                <th>{{ member.document_type }}</th>
                <th>{{ member.document_number}}</th>
                <th>{{ member.gender }}</th>
                <th>{%if member.is_active -%} {{"Activo"}}
                    {%else -%}
                    {{"Bloqueado"}}
                    {% endif %}</th>
                <th>{%if member.user_id %}
                    {{member.user.email}}
                    {% endif %}
                </th>    
                <th>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                          aria-expanded="false">
                          Operaciones
                        </button>
                        <ul class="dropdown-menu">
                            {% if not member.user_id and member.is_active %}
                            <li><a class="dropdown-item" href="{{url_for('users.link_user', id=member.membership_number)}}">Asignar usuario</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{{ url_for('members.update',
                                member_id=member.membership_number)}}">Editar</a>
                            <li><a class="dropdown-item" href="{{url_for('movements.member_balance', member_id=member.membership_number)}}">Pagos</a></li>
                        </ul>
                    </div>
                </th>
            </tr>
            
        </tbody>
        <thead> 
            <tr>
                <th>Domicilio</th>
                <th>Email</th>
                <th>Teléfono</th>
            </tr>
        </thead>
        <br>
        <br>
        <tbody>
            <tr>
                <th>{{ member.address }}</th>
                <th>{{ member.email }}</th>
                <th>{{ member.phone_number }}</th>
            </tr>
        </tbody>
    </table>
    {% else %}
    <h1>Socio No Encontrado.</h1>
    {% endif %}

</div>

{% endblock content%}

admin/src/web/templates/members/search.html
{% extends "layout.html" %}
{% block title %}Buscar un Socio{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
  <h1 class="text-muted text-center"> Buscar Socio </h1>
  <div class="row my-5">
    <form class="d-flex" role="search" action="{{ url_for('members.filter_by_doc')}}" method="post">
      {{ filter_form.document_number(class="form-control me-2", placeholder="Ingrese el dni del socio que desea buscar.")}}
      {{filter_form.document_type.label}} {{ filter_form.document_type(class="")}}
      {{filter_form.hidden_tag()}}
      <button class="btn btn-outline-success" type="submit">Buscar Socio</button> 
    </form>  
  </div>
  <div class="row my-5">
    <a href="{{url_for('members.index')}}"> Volver </a>
  </div>


  </div>


{% endblock %}

admin/src/web/templates/members/update.html
{% extends "layout.html" %}
{% block title %}Actualizar Socio{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Actualización de Socio N° {{ member_id }}</h1>
        </div>
    </div>
    <form action="{{ url_for('members.update', member_id=member_id)}}" method="post">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col">
                <div class="from-group mb-3">
                    {{ form.first_name.label}}
                    {{ form.first_name(class_="form-control", placeholder="Nombre")}}
                </div>
            </div>
        </div>
        <div class="row">    
            <div class="col">
                <div class="from-group mb-3">
                    {{ form.last_name.label}}
                    {{ form.last_name(class_="form-control", placeholder="Apellido")}}
                </div>
            </div>
        </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col">
                <div class="form-group mb-3">
                    {{ form.document_type.label}}
                    {{ form.document_type(class_="form-control")}}
                </div>
            </div>
            <div class="col">
                <div class="form-group mb-3">
                    {{ form.document_number.label}}
                    {{ form.document_number(class_="form-control", placeholder="Número de Documento")}}
                </div>
            </div>
            <div class="col">
                <div class="form-group mb-3">
                    {{ form.gender.label }}
                    {{ form.gender(class_="form-control")}}
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.address.label }}
                    {{ form.address(class_="form-control", placeholder="Domicilio")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.email.label }}
                    {{ form.email(class_="form-control", placeholder="Email")}}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="form-group mb-3">
                    {{ form.phone_number.label }}
                    {{ form.phone_number(class_="form-control", placeholder="Télefono")}}
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                {{ form.submit(class="btn btn-success", value="Actualizar") }}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center">
                <a href="{{url_for('members.index')}}"> Volver </a>
            </div>
        </div>
    </form>
</div>



{% endblock %}

admin/src/web/templates/members/view_report.html
<!DOCTYPE html>
<html>
    <head>
        <title>Visualizar Reporte</title>
        <meta charset="UTF-8">
    </head>
       <body>
          <embed src="../../../../public/{{filename}}" type="application/pdf" width="100%" height="600px"/>
       </body> 

</html>