admin/src/web/forms/user.py
from wsgiref.validate import validator
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, EmailField, PasswordField, SelectMultipleField
from wtforms.validators import DataRequired, Length, Email


class UserBaseForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Length(max=50, min=3), Email()]
    )
    username = StringField(
        "Usuario", validators=[DataRequired(), Length(max=30, min=3)]
    )
    first_name = StringField(
        "Nombre", validators=[DataRequired(), Length(max=75, min=3)]
    )
    last_name = StringField(
        "Apellido", validators=[DataRequired(), Length(max=75, min=3)]
    )


class CreateUserForm(UserBaseForm):
    roles = SelectField(
        "Rol",
        choices=[
            ("Administrador", "Administrador"),
            ("Operador", "Operador"),
            ("Socio", "Socio"),
        ],
        validators=[DataRequired()],
    )
    submit = SubmitField("Crear usuario")


class UpdateUserForm(UserBaseForm):
    submit = SubmitField("Actualizar usuario")


class SearchUserForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Length(max=50, min=3), Email()]
    )
    submit = SubmitField("Buscar usuario")


class FilterUsersForm(FlaskForm):
    filter = SelectField(
        "filter",
        choices=[
            ("Activo", "Activo"),
            ("Bloqueado", "Bloqueado"),
            ("Mostrar Todos", "Mostrar Todos"),
        ],
    )
    submit = SubmitField("Filtrar")


class AddRolesForm(FlaskForm):
    roles = SelectField(
        "Rol",
        choices=[
            ("Administrador", "Administrador"),
            ("Operador", "Operador"),
            ("Socio", "socio"),
        ],
        validators=[DataRequired()],
    )
    submit = SubmitField("Crear usuario")


class DeleteRolesForm(FlaskForm):
    role = StringField("role", validators=[DataRequired()])
    submit = SubmitField("Eliminar rol")


class LoginForm(FlaskForm):
    username = StringField(
        "username", validators=[DataRequired(), Length(max=30, min=3)]
    )
    password = PasswordField("password", validators=[DataRequired()])
    submit = SubmitField("Login")

class UnlinkMemberForm(FlaskForm):
    member = StringField("member", validators=[DataRequired()])
    submit = SubmitField("Desvincular Socio")

class UpdatePassForm(FlaskForm):
    current_password = PasswordField("Contraseña Actual", validators=[DataRequired()])
    new_password = PasswordField("Contraseña Nueva", validators=[DataRequired(), Length(min=6)])
    confirm_password = PasswordField("Confirmar contraseña", validators=[DataRequired(), Length(min=6)])
    submit = SubmitField("Cambiar")

admin/src/web/controllers/user.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask import session
from services.movement import MovementService

from src.services.settings import SettingsService
from src.services.utils import hash_pass
from src.services.utils import verify_pass
from src.web.helpers.auth import is_member, login_required, verify_permission
from src.services.user import UserService
from src.services.movement import MovementService
from src.services.member import MemberService
from src.web.forms.user import (
    CreateUserForm,
    UpdateUserForm,
    SearchUserForm,
    FilterUsersForm,
    AddRolesForm,
    DeleteRolesForm,
    UnlinkMemberForm,
    UpdatePassForm
)
from src.web.forms.member import FilterSearchForm
from src.errors import database


user_blueprint = Blueprint("users", __name__, url_prefix="/users")

service = UserService()
member_service = MemberService()
settings = SettingsService()
movementService = MovementService()


@user_blueprint.route("/", methods=["GET"])
@login_required
@verify_permission("user_index")
def index():
    filter_form = FilterUsersForm()
    """Render de la lista de usuarios paginada"""
    filter = request.args.get("filter")
    page = request.args.get("page", 1, type=int)
    users_paginator = service.list_paginated_users(
        page, settings.get_items_per_page(), "users.index", filter
    )
    return render_template(
        "users/index.html",
        filter_form=filter_form,
        paginator=users_paginator,
    )


@user_blueprint.route("/filter_users_by", methods=["POST"])
@login_required
@verify_permission("user_search")
def users_filter_by():
    filter_form = FilterUsersForm()

    if filter_form.validate_on_submit:

        page = request.args.get("page", 1, type=int)
        filter = filter_form.filter.data
        users_paginator = service.list_paginated_users(
            page, settings.get_items_per_page(), "users.index", filter
        )
        return render_template(
            "users/index.html",
            paginator=users_paginator,
            filter_form=filter_form,
        )


@user_blueprint.route("/add", methods=["POST", "GET"])
@login_required
@verify_permission("user_create")
def users_add():
    """Agrega usuarios mediante el formulario"""
    form = CreateUserForm()

    if form.validate_on_submit():

        role = service.find_role_by_name(form.roles.data)
        email = form.email.data
        username = form.username.data
        first_name = form.first_name.data
        password = hash_pass(form.email.data)
        last_name = form.last_name.data
        roles = [role]

        try:
            service.create_user(
                email=email,
                username=username,
                password=password,
                first_name=first_name,
                last_name=last_name,
                roles=roles,
            )
            flash("Usuario creado con éxito!", "success")
        except database.ExistingData as e:
            flash(e, "danger")
    return render_template("users/add_user.html", form=form)


@user_blueprint.route("/update/<id>", methods=["POST", "GET"])
@login_required
@verify_permission("user_update")
def users_update(id):
    form = UpdateUserForm()
    user = service.find_user_by_id(id)

    if request.method == "POST":
        if form.validate_on_submit():
            email = form.email.data
            username = form.username.data
            first_name = form.first_name.data
            last_name = form.last_name.data

            try:
                service.update_user(
                    id=id,
                    email=email,
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                )
                flash("Usuario actualizado con éxito!", "success")
            except database.ExistingData as e:
                flash(e, "danger")

    return render_template("users/update.html", user=user, form=form)


@user_blueprint.route("/block_user/<id>", methods=["GET"])
@login_required
@verify_permission("user_update")
def users_block(id):
    user = service.find_user_by_id(id)

    try:

        user_session = session["user"]
        service.block_user(id, user_session)
        if user.is_active == False:
            flash("Usuario bloqueado con éxito", "success")
        else:
            flash("Usuario desbloqueado con éxito", "success")
    except database.PermissionDenied as e:
        flash(e, "danger")

    return redirect(url_for("users.index"))


@user_blueprint.route("/search_user", methods=["POST", "GET"])
@login_required
@verify_permission("user_search")
def users_search():
    search_form = SearchUserForm()
    unlink_form = UnlinkMemberForm()

    if request.method == "POST":
        delete_roles_form = DeleteRolesForm()
        add_roles_form = AddRolesForm()

        if search_form.validate_on_submit():
            email = search_form.email.data
            user = service.find_user_byEmail(email)
            return render_template(
                "users/user_info.html",
                user=user,
                add_roles_form=add_roles_form,
                delete_roles_form=delete_roles_form,
                unlink_form=unlink_form
            )
    else:
        return render_template("users/search.html", search_form=search_form)


@user_blueprint.route("/user_info/<id>", methods=["GET", "POST"])
@login_required
@verify_permission("user_show")
def user_info(id):
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()

    user = service.find_user_by_id(id)
    return render_template(
        "users/user_info.html",
        user=user,
        add_roles_form=add_roles_form,
        delete_roles_form=delete_roles_form,
        unlink_form=unlink_form,
    )


@user_blueprint.route("/add_roles/<id>", methods=["POST", "GET"])
@login_required
@verify_permission("user_update")
def users_add_roles(id):
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()
    user = service.find_user_by_id(id)

    if request.method == "POST":

        if add_roles_form.validate_on_submit:
            role = add_roles_form.roles.data

            try:
                service.add_role(id, role)
                flash("Rol agregado con éxito!", "success")
            except database.ExistingData as e:
                flash(e, "danger")
            except database.PermissionDenied as e:
                flash(e, "danger")
        return render_template(
            "users/user_info.html",
            user=user,
            add_roles_form=add_roles_form,
            delete_roles_form=delete_roles_form,
            unlink_form=unlink_form,
        )
    else:
        return render_template(
            "users/user_info.html",
            user=user,
            add_roles_form=add_roles_form,
            delete_roles_form=delete_roles_form,
            unlink_form=unlink_form,
        )


@user_blueprint.route("/delete_roles/<id>", methods=["POST", "GET"])
@login_required
@verify_permission("user_update")
def users_delete_roles(id):
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()
    user = service.find_user_by_id(id)
    roles = service.list_user_roles(id)
    if request.method == "POST":
        if delete_roles_form.validate_on_submit:
            try:
                role = delete_roles_form.role.data
                service.remove_role(id, role)
                flash("Rol eliminado con éxito!", "success")
            except database.PermissionDenied as e:
                flash(e, "danger")
    return render_template(
        "users/user_info.html",
        user=user,
        roles=roles,
        delete_roles_form=delete_roles_form,
        add_roles_form=add_roles_form,
        unlink_form=unlink_form,
    )


@user_blueprint.route("/profile", methods=["GET"])
@login_required
def profile():
    delete_roles_form = DeleteRolesForm()
    add_roles_form = AddRolesForm()
    unlink_form = UnlinkMemberForm()
    id = session["user"]

    user = service.find_user_by_id(id)
    return render_template(
        "users/profile.html",
        user=user,
        delete_roles_form=delete_roles_form,
        add_roles_form=add_roles_form,
        unlink_form=unlink_form
    )


@user_blueprint.route("/delete/<id>", methods=["GET"])
@login_required
@verify_permission("user_destroy")
def delete(id):
    filter_form = FilterUsersForm()
    session_id = session["user"]

    try:
        service.delete(id, session_id)
        flash("Usuario eliminado con éxito!", "success")
    except database.PermissionDenied as e:
        flash(e, "danger")
    users = service.list_users()
    return render_template("users/index.html", users=users, filter_form=filter_form)


@user_blueprint.route("/estado_societario/", methods=["GET"])
@login_required
@is_member
def memberState():
    filter_form = FilterSearchForm()
    page = request.args.get("page", 1, type=int)
    filter = request.args.get("filter")
    search = request.args.get("search")
    member_paginator = member_service.list_paginated_members(
        page, settings.get_items_per_page(), "users.memberState", filter, search, True
    )
    return render_template(
        "users/member_state.html", filter_form=filter_form, paginator=member_paginator
    )

@user_blueprint.route("/lista_movimientos/<member_id>", methods=["GET"])
@login_required
def viewMovements(member_id):
    member = member_service.get_by_membership_number(member_id)
    balance = movementService.get_balance(member, all=True)
    page = request.args.get("page", 1, type=int)

    paginator = movementService.list_paginated_movements(
        page,
        settings.get_items_per_page(),
        'users.viewMovements',
        member
    )

    return render_template(
        "users/view_movements.html",
        member=member,

admin/src/web/templates/users/add_user.html
{% extends "layout.html" %}
{% block title %}Agregar usuario{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="container">
    <h1 class="text-center" > Nuevo usuario</h1>
    <div class="row my-2">
      <form action="{{ url_for('users.users_add')}}" method="post">
        {{ form.hidden_tag() }}
      <div class="form-group my-2">
        {{ form.email.label }} {{ form.email(class_="form-control") }}
      </div>
      <div class="form-group my-2">
        {{ form.username.label }} {{ form.username(class_="form-control") }}
      </div>
      <div class="form-group my-2">
        {{ form.first_name.label }} {{ form.first_name(class_="form-control") }}
      </div>
      <div class="form-group my-2">
        {{ form.last_name.label }} {{ form.last_name(class_="form-control") }}
      </div>
      <div class="form-group my-2">
        {{ form.roles.label }} {{ form.roles(class_="form-control") }}
      </div>
      <div class="row my-3 mx-auto">
        <input type="submit" value="Crear Usuario" class="btn btn-outline-success">
      </div>
    </form>

    
  </div>

  <div class="row my-5">
    <a href="{{url_for('home')}}"> Volver al inicio </a></li>
  </div>
    
</div>


{% endblock %}

admin/src/web/templates/users/index.html
{% extends "layout.html" %}
{% block title %}Usuarios{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<h1 class="text-center">Usuarios</h1>

<div class="container">
  <div class="row my-5">
    <h3>Filtrar listado por: </h3>
    <form action="{{ url_for('users.users_filter_by')}}" method="post">
      <div class="form group">
        {{ filter_form.filter(class="", selected="selected")}}
        {{filter_form.hidden_tag()}}
        <button class="btn btn-outline-secondary block" type="submit">Filtrar</button>
      </div>
    </form>
  </div>

  {% if paginator.items %}

  <div class="row my-3">
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Email</th>
          <th>Nombre de Usuario</th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Estado</th>
          <th>Operaciones</th>
        </tr>
      </thead>
      <tbody>
        {% for user in paginator.items %}
        <tr>
          <th>{{ user.id }}</th>
          <th>{{ user.email }}</th>
          <th>{{ user.username }}</th>
          <th>{{ user.first_name }}</th>
          <th>{{ user.last_name }}</th>
          {% if user.is_admin %}
          <th>{%if user.is_active -%} {{"Activo"}}
            {%else -%}
            {{"Bloqueado"}}
            {% endif %}
          </th>
          {% else %}
          <th>


            <!-- Button trigger modal -->
            <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal"
              data-bs-target="#staticBackdrop{{user.id}}">
              {% if user.is_active%}
              {{"Activo"}}
              {% else %}
              {{"Bloqueado"}}
              {% endif %}
            </button>

            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop{{user.id}}" data-bs-backdrop="static"
              data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">
                      {% if user.is_active%}
                      {{"Bloquear usuario"}}
                      {% else %}
                      {{"Activar usuario"}}
                      {% endif %}
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    Está seguro de que desea
                    {% if user.is_active%}
                    {{" bloquear el usuario?"}}
                    {% else %}
                    {{" activar el usuario?"}}
                    {% endif %}
                    {{ user.id }}
                  </div>
                  <form
                    action="{{url_for('users.users_block', id=user.id)}}">
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                      <button type="submit" class="btn btn-primary">Sí</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

          </th>
          {% endif %}
          <th>
            <div class="dropdown">
              <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Operaciones
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{url_for('users.user_info', id=user.id)}}">Ver usuario</a></li>
                <li><a class="dropdown-item" href="{{url_for('users.users_update', id=user.id)}}">Editar Usuario</a>
                </li>
                {% if user.is_member and user.is_active%}
                <li><a class="dropdown-item" href="{{url_for('users.link_members', id=user.id)}}">Asignar Socios</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </th>
          </th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


  <div class="row my-3">

    {% include('partials/paginator.html') %}

    {% else %}
    <h2>No hay usuarios para mostrar</h2>

    {% endif %}



  </div>
  <div class="row my-5">
    <a href="{{url_for('home')}}"> Volver al inicio </a>
  </div>
</div>

{% endblock %}

admin/src/web/templates/users/link_members.html
{% extends "layout.html" %}
{% block title %}Asignar socios{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
  <h1 class="text-center" >Asignar socios al usuario: {{user.username}}</h1>
  <div class="row my-5">
    
    {% if members %}
    <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th>#Nro de Socio</th>
            <th>Nombre</th>
            <th>Apellido</th>
          </tr>
        </thead>
        <form action="{{url_for('users.link_members', id=user.id)}}" method="post" >
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          <tbody>
            {% for member in members %}  
            <tr>
              <th>{{ member.membership_number }}</th>
              <th>{{ member.first_name }}</th>
              <th>{{ member.last_name }}</th>
              <th>
                <input type="checkbox", value="{{member.membership_number}}", name="selected">
              </th>
            </tr>
            {% endfor %}     
            </tbody> 
                
            <input type="submit" value="Seleccionar">
        </form> 
    </table>
  
    {% else %}
  <h2 class="text-muted text-center">No hay usuarios para mostrar</h2>
  {% endif %}
  </div>
  <div class="row my-5">
    <a href="{{url_for('users.index')}}"> Volver </a>
  </div>
  
</div>


{% endblock %}

admin/src/web/templates/users/member_state.html
{% extends "layout.html" %}
{% block title %}Estado societario{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
    
        <div class="col-12 text-center">
            <h1>Estado societario de los socios administrados</h1>
        </div>  
   <table class="table table-hover">
        <thead>
            <tr>
                <th>N° de Socio</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo de Documento</th>
                <th>N° de Documento</th>
                <th>Género</th>
                <th>Movimientos y saldos</th>
            </tr>
        </thead>
        <tbody>
            {% for member in paginator.items %}
            <tr>
                <td>{{ member.membership_number }}</td>
                <td>{{ member.first_name }}</td>
                <td>{{ member.last_name }}</td>
                <td>{{ member.document_type }}</td>
                <td>{{ member.document_number}}</td>
                <td>{{ member.gender }}</td>
                <td><a href="{{url_for('users.viewMovements', member_id=member.membership_number)}}">Ver</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include('partials/paginator.html') %}
    <br>
    <br>
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-center">
            <a class="btn btn-primary btn-sm" href="{{url_for('home')}}"> Volver </a>
        </div>
    </div>
</div> 

{% endblock content %}

admin/src/web/templates/users/roles.html
<div class="row my-3">

    <div class="col-6 ">
        <h2 > Roles Asignados </h2>
        <table class="table table-hover table-sm">
            <tbody>
                <tr>
                    {% for role in user.roles %}
                <tr>
                    <th>{{ role.name }}</th>
                    <th>
                        <form action="{{url_for('users.users_delete_roles', id=user.id)}}" method="post">
                            <div class="form-group">
                                {{ delete_roles_form.hidden_tag() }}
                                {{ delete_roles_form.role(type="hidden", value=role.name) }}
                            </div>
                            {% if user.roles|length > 1 %}
                            {% if (role.name == "Socio" and not user.has_members) or (not role.name =="Socio") %}
                            <button type="submit" class="btn btn-outline-danger"> Desasignar</button>
                            {% endif %}
                            {% endif %}
                        </form>
                    </th>
                </tr>
                {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
    {% if user.roles|length < 3 %}
    <div class="col-6 mx-auto">

        <h2 >Asignar nuevo rol </h2>
        <form action="{{ url_for('users.users_add_roles', id=user.id)}}" method="post">
            <div class="form group">
                {{add_roles_form.hidden_tag()}}
                {{add_roles_form.roles}}
                <button class="btn btn-outline-success">Asignar</button>
            </div>
        </form>
    </div>
    {% endif %}
</div>

admin/src/web/templates/users/search.html
{% extends "layout.html" %}
{% block title %}Buscar un Usuario{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
  <h1 class="text-center" > Buscar usuario </h1>
  <div class="row my-5">
    
    <form class="d-flex" role="search" action="{{ url_for('users.users_search')}}" method="post">
      {{ search_form.email(class="form-control me-2", placeholder="Ingrese el email del usuario que desea buscar")}}
      {{search_form.hidden_tag()}}
      <button class="btn btn-outline-success" type="submit">Buscar Usuario</button> 
    </form>
  </div>

  <div class="row my-5">
    <a href="{{url_for('users.index')}}"> Volver </a>
  </div>

</div>

{% endblock %}

admin/src/web/templates/users/update.html
{% extends "layout.html" %}
{% block title %}Editar Usuario{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container">
  <h1 class="text-center" >Editar Usuario</h1>
    <div class="row my-5">
      <form action="{{ url_for('users.users_update', id=user.id)}}" method="post">
        <div class="form-group my-2" >
            {{ form.email.label }} {{ form.email(class_="form-control", value= user.email) }}
          </div>
          <div class="form-group my-2">
            {{ form.username.label }} {{ form.username(class_="form-control", value= user.username) }}
          </div>
          <div class="form-group my-2">
            {{ form.first_name.label }} {{ form.first_name(class_="form-control", value= user.first_name) }}
          </div>
          <div class="form-group my-2">
            {{ form.last_name.label }} {{ form.last_name(class_="form-control", value= user.last_name) }}
          </div>
            {{ form.hidden_tag() }}
          <div class="row my-3 mx-auto">
            <input type="submit" value="Actualizar Usuario" class="btn btn-outline-success">
          </div>     
      </form>
    </div>
    <div class="row my-5">
      <a href="{{url_for('users.index')}}"> Volver </a>
    </div>

</div>

{% endblock %}

admin/src/web/templates/users/user_info.html
{% extends "layout.html" %}
{% block title %}Información de usuario{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="container">

  <h1 class="text-center">Información de usuario</h1>

  {% if user %}
  <div class="row my-5">
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th>#ID </th>
          <th>Email</th>
          <th>Usuario</th>
          <th>Estado</th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Operaciones</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>{{ user.id }}</th>
          <th>{{ user.email }}</th>
          <th>{{ user.username }}</th>
          <th>{%if user.is_active -%} {{"Activo"}}
            {%else -%}
            {{"Bloqueado"}}
            {% endif %}</th>
          <th>{{ user.first_name }}</th>
          <th>{{ user.last_name }}</th>
          <th>
            <div class="dropdown">
              <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Operaciones
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{url_for('users.users_update', id=user.id)}}">Editar Usuario</a>
                </li>
                {% if user.is_member and user.is_active %}
                <li><a class="dropdown-item" href="{{url_for('users.link_members', id=user.id)}}">Asignar Socios</a>
                </li>
                {% endif %}
                <!-- {% if not user.is_admin %}
                    <li><a class="dropdown-item" href="{{url_for('users.users_block', id=user.id)}}">
                        {% if user.is_active %}
                        {{"Bloquear"}}
                        {% else %}
                        {{"Desbloquear"}}
                        {% endif %}</a>
                    </li>
                    {% endif %} -->
              </ul>
            </div>
          </th>
          </th>
        </tr>
      </tbody>
    </table>
  </div>

  {% for role in user.roles %}
  {% if role.name == "Socio" %}
  {% if user.has_members %}
  <div class="row my-3">
    <h1>Socios vinculados</h1>
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th>Socios </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          {% for member in user.members %}
          <th>{{member.document_type}}: {{ member.document_number }}</th>
          <th>
            <!-- Button trigger modal -->
            <div class="col-3 mx-right">
              <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal"
                data-bs-target="#exampleModal{{member.membership_number}}">
                Desvincular Socio
              </button>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal{{member.membership_number}}" tabindex="-1" aria-labelledby="exampleModalLabel"
              aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title" id="exampleModalLabel">Desvincular socio</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    ¡ATENCIÓN!
                    Si desvincula el socio, se perderá la información asociada. 
                    Está seguro que de desea desvincula el socio {{member.document_type}}: {{ member.document_number }}?
                  </div>
                  <form action="{{url_for('users.unlink_member', id=user.id)}}" method="post">
                    <div class="form-group">
                      {{ unlink_form.hidden_tag() }}
                      {{ unlink_form.member(type="hidden", value=member.membership_number) }}
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                      <button type="submit" class="btn btn-outline-danger">Desvincular Socio</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </th>
          {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>
  {% endif %}
  {% endif %}
  {% endfor %}

  {% include('users/roles.html') %}

  <div class="row mx-auto">
    <h3 class="text-muted"> Eliminar Usuario</h3>
    <p class="lead"><strong>Si elimina el usuario, se perderá toda la Información asociada al mismo.</strong></p>
    <!-- Button trigger modal -->
    <div class="col-3 mx-right">
      <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Eliminar Usuario
      </button>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title" id="exampleModalLabel">Eliminar Usuario</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            ¡ATENCIÓN!
            Esta acción es irreversible.
            Está seguro que de desea eliminar el usuario {{user.email}}?
          </div>
          <form action="{{url_for('users.delete', id=user.id)}}">

            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-outline-danger">Eliminar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="row">
    <h2>Usuario Inexistente</h2>
  </div>
  {% endif %}
  <div class="row my-3">
    <a href="{{url_for('users.index')}}"> Volver </a>
  </div>
</div>
{% endblock %}